tests/utils/qmain.cpp: Add missing include for libintl.h
Fixes the following build error under musl libc:

  ../../../tests/utils/qmain.cpp: In function 'int main(int, char**)':
  ../../../tests/utils/qmain.cpp:47:5: error: 'bindtextdomain' was not declared in this scope
     47 |     bindtextdomain(GETTEXT_PACKAGE, LOCALEDIR);
        |     ^~~~~~~~~~~~~~
  ../../../tests/utils/qmain.cpp:48:5: error: 'textdomain' was not declared in this scope
     48 |     textdomain(GETTEXT_PACKAGE);
        |     ^~~~~~~~~~